#!/usr/bin/env bash
# This script checks the properties of a file named 'school' and prints information about it.

# Check if the file 'school' exists
if [ -e school ]; then
    echo "school file exists"

    # Check if the file is empty or not
    if [ -s school ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the file is a regular file
    if [ -f school ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
